defaults:
  - override hydra/hydra_logging: "none"
  - override hydra/job_logging: "custom"

hydra:
  run:
    dir: ./logs/hyperparameters_tuning/${now:%Y-%m-%d}/${now:%H-%M-%S}

data_filepath: "data/processed/" # the / at the end is necessary
base_model_filepath: "models/base"
test_size: 0.2
random_seed: 2024 # applied for all models
label_col: "price"

model_type: ridge.pkl
metric: "mae"

pipeline_step_names: ["ua_clean", "ma_clean", "col_dropper", "cat_handler", "nan_handler", "final_ct"]
preprocessor_name: "preprocessor"
predictor_name: "predictor"

hyperparameter_tuning:
  name: "my_ridge_high"
  param_grid:
    model:
      alpha: [0]
    ma_clean:
      finalize_flag: [True, False]
    final_ct:
      numerical_encoder: ["passthrough", "standardscaler"]
  cv_no: 10
  random_seed: 2024
  n_jobs: -1
  return_train_score: True
  verbose: 0
  refit: False
