defaults:
  - override hydra/hydra_logging: "none"
  - override hydra/job_logging: "custom"

hydra:
  run:
    dir: ./logs/hyperparameters_tuning/${now:%Y-%m-%d}/${now:%H-%M-%S}

test_size: 0.2
random_seed: 2024 # applied for all models
label_col: "price"
initial_build_verbose: 2
features_builder_verbose: 2

model_type: ridge.pkl
metric: "mae"

hyperparameter_tuning:
  name: "my_ridge_high"
  param_grid:
    model:
      alpha: [0, 0.5, 1]
  cv_no: 10
  random_seed: 2024
  n_jobs: -1
  return_train_score: True
  verbose: 2
  refit: False
