defaults:
  - override hydra/hydra_logging: "none"
  - override hydra/job_logging: "custom"

hydra:
  run:
    dir: ./logs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}

test_size: 0.2
random_seed: 2024 # applied for all models
label_col: "price"
initial_build_verbose: 2

models:
  - name: "my_ridge_high"
    type: ridge.pkl
    hyperparameters:
      alpha: 1
  
  - name: "my_ridge_low"
    type: ridge.pkl
    hyperparameters:
      alpha: 0

  - name: "my_ridge_medium"
    type: ridge.pkl
    hyperparameters:
      alpha: 0.5
metric: "mae"

features_builder:
  ua_cleaner:
  ma_cleaner:
    low_kilometerage_cars_flag: True
    high_seats_cars_flag: True
    oldtimers_flag: True
    finalize_flag: True
  final_ct:
    numerical_encoder: "passthrough"
    nominal_encoder: "ordinal"
  verbose: 2