defaults:
  - override hydra/hydra_logging: none
  - override hydra/job_logging: custom

hydra:
  run:
    dir: ./logs/scraper/${now:%Y-%m-%d}/${now:%H-%M-%S}

index_page_url: "https://www.polovniautomobili.com"
sp_offset: 1800

scraper_processes:
  - socks_port: 9250
    options:
    - permissions.default.image: 2
      permissions.default.stylesheet: 2

  - socks_port: 9350
    options:
    - permissions.default.image: 2
      permissions.default.stylesheet: 2

  - socks_port: 9450
    options:
    - permissions.default.image: 2
      permissions.default.stylesheet: 2

tor:
  circuit_wait_time: 10
  tbb_path: ./tor-browser
  url_listing_load_timeout: 9
  url_sp_load_timeout: 15
  headless_mode: True
  start_timeout: 120
